name = "cca-landing-page"
compatibility_date = "2025-04-17" # Consider updating to today's date
compatibility_flags = ["nodejs_compat"]

# Directory where the built static site is output by Next.js
pages_build_output_dir = "out"